type Category = { name: string; img:any }

export const categories: Category[] = [
    {name: '3D 도면설계', img:"/categoryIcons/도면설계.png"},
    {name: '종합인테리어', img:"/categoryIcons/종합인테리어.png"},
    {name: '철거', img:"/categoryIcons/철거.png"},
    {name: '소방설비', img:"/categoryIcons/소방설비.png"},
    {name: '설비', img:"/categoryIcons/설비.png"},
    {name: '전기', img:"/categoryIcons/전기.png"},
    {name: '샤시', img:"/categoryIcons/샤시.png"},
    {name: '목공', img:"/categoryIcons/목공.png"},
    {name: '욕실', img:"/categoryIcons/욕실.png"},
    {name: '타일', img:"/categoryIcons/타일.png"},
    {name: '페인트', img:"/categoryIcons/페인트.png"},
    {name: '마루', img:"/categoryIcons/마루.png"},
    {name: '필름', img:"/categoryIcons/필름.png"},
    {name: '도배', img:"/categoryIcons/도배.png"},
    {name: '조명', img:"/categoryIcons/조명.png"},
    {name: '장판', img:"/categoryIcons/장판.png"},
    {name: '싱크', img:"/categoryIcons/싱크.png"},
    {name: '닥트', img:"/categoryIcons/닥트.png"},
    {name: '금속공사', img:"/categoryIcons/금속공사.png"},
    {name: '간판', img:"/categoryIcons/간판.png"},
    {name: '천막/어닝', img:"/categoryIcons/천막어닝.png"},
    {name: '냉난방', img:"/categoryIcons/냉난방.png"},
    {name: 'CCTV', img:"/categoryIcons/cctv.png"},
    {name: '입주청소', img:"/categoryIcons/입주청소.png"},
    {name: '도어락', img:"/categoryIcons/도어락.png"},
    {name: '카고크레인', img:"/categoryIcons/카고크레인.png"},
    {name: '사다리차', img:"/categoryIcons/사다리차.png"},
    {name: '고소작업차', img:"/categoryIcons/고소작업차.png"}    
]
export const categories2: Category[] = [
    {name: '3D 도면설계', img:"/categoryIcons/도면설계.png"},
    {name: '종합인테리어', img:"/categoryIcons/종합인테리어.png"},
    {name: '철거', img:"/categoryIcons/철거.png"},
    {name: '설비', img:"/categoryIcons/설비.png"},
    {name: '전기', img:"/categoryIcons/전기.png"},
    {name: '샤시', img:"/categoryIcons/샤시.png"},
    {name: '목공', img:"/categoryIcons/목공.png"},
    {name: '욕실', img:"/categoryIcons/욕실.png"},
    {name: '타일', img:"/categoryIcons/타일.png"},
    {name: '페인트', img:"/categoryIcons/페인트.png"},
    {name: '마루', img:"/categoryIcons/마루.png"},
    {name: '필름', img:"/categoryIcons/필름.png"},
    {name: '도배', img:"/categoryIcons/도배.png"},
    {name: '조명', img:"/categoryIcons/조명.png"},
    {name: '장판', img:"/categoryIcons/장판.png"},
    {name: '싱크', img:"/categoryIcons/싱크.png"},
    {name: '냉난방', img:"/categoryIcons/냉난방.png"},
    {name: 'CCTV', img:"/categoryIcons/cctv.png"},
    {name: '입주청소', img:"/categoryIcons/입주청소.png"},
    {name: '도어락', img:"/categoryIcons/도어락.png"},
    {name: '카고크레인', img:"/categoryIcons/카고크레인.png"},
    {name: '사다리차', img:"/categoryIcons/사다리차.png"},
    {name: '고소작업차', img:"/categoryIcons/고소작업차.png"}    
]